FROM python:3.12.3-slim

WORKDIR /app

# Copiar el archivo de dependencias y luego instalarlas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar los archivos de tu script y modelos
COPY crearDB_poo.py .
COPY CrearTablasDb.py .
COPY config.py .

# Ejecutar el script de inicialización
CMD ["python", "crearDB_poo.py"]

